INSERT INTO `countries` VALUES ('AD', 'andorra', 'Andorra', '42.5', '1.5', '7');
INSERT INTO `countries` VALUES ('AE', 'united-arab-emirates', 'United Arab Emirates', '24', '54', '7');
INSERT INTO `countries` VALUES ('AF', 'afghanistan', 'Afghanistan', '33', '65', '35');
INSERT INTO `countries` VALUES ('AG', 'antigua-and-barbuda', 'Antigua and Barbuda', '17.05', '-61.8', '7');
INSERT INTO `countries` VALUES ('AI', 'anguilla', 'Anguilla', '18.25', '-63.1667', '0');
INSERT INTO `countries` VALUES ('AL', 'albania', 'Albania', '41', '20', '12');
INSERT INTO `countries` VALUES ('AM', 'armenia', 'Armenia\r\n', '40', '45', '11');
INSERT INTO `countries` VALUES ('AN', 'netherlands-antilles', 'Netherlands Antilles\r\n', '12.25', '-68.75', '0');
INSERT INTO `countries` VALUES ('AO', 'angola', 'Angola\r\n', '-12.5', '18.5', '17');
INSERT INTO `countries` VALUES ('AQ', 'antarctica', 'Antarctica\r\n', '-90', '0', '0');
INSERT INTO `countries` VALUES ('AR', 'argentina', 'Argentina\r\n', '-34', '-64', '24');
INSERT INTO `countries` VALUES ('AS', 'american-samoa', 'American Samoa\r\n', '-14.3333', '-170', '0');
INSERT INTO `countries` VALUES ('AT', 'austria', 'Austria\r\n', '47.3333', '13.3333', '9');
INSERT INTO `countries` VALUES ('AU', 'australia', 'Australia\r\n', '-27', '133', '8');
INSERT INTO `countries` VALUES ('AW', 'aruba', 'Aruba\r\n', '12.5', '-69.9667', '0');
INSERT INTO `countries` VALUES ('AX', 'aland-islands', 'Aland Islands\r\nÅland Islands', '0.1', '0.1', '0');
INSERT INTO `countries` VALUES ('AZ', 'azerbaijan', 'Azerbaijan\r\n', '40.5', '47.5', '71');
INSERT INTO `countries` VALUES ('BA', 'bosnia-and-herzegovina', 'Bosnia and Herzegovina\r\n', '44', '18', '2');
INSERT INTO `countries` VALUES ('BB', 'barbados', 'Barbados\r\n', '13.1667', '-59.5333', '11');
INSERT INTO `countries` VALUES ('BD', 'bangladesh', 'Bangladesh\r\n', '24', '90', '64');
INSERT INTO `countries` VALUES ('BE', 'belgium', 'Belgium\r\n', '50.8333', '4', '12');
INSERT INTO `countries` VALUES ('BF', 'burkina-faso', 'Burkina Faso\r\n', '13', '-2', '45');
INSERT INTO `countries` VALUES ('BG', 'bulgaria', 'Bulgaria\r\n', '43', '25', '29');
INSERT INTO `countries` VALUES ('BH', 'bahrain', 'Bahrain\r\n', '26', '50.55', '12');
INSERT INTO `countries` VALUES ('BI', 'burundi', 'Burundi\r\n', '-3.5', '30', '16');
INSERT INTO `countries` VALUES ('BJ', 'benin', 'Benin\r\n', '9.5', '2.25', '6');
INSERT INTO `countries` VALUES ('BM', 'bermuda', 'Bermuda\r\n', '32.3333', '-64.75', '11');
INSERT INTO `countries` VALUES ('BN', 'brunei-darussalam', 'Brunei Darussalam\r\n', '4.5', '114.6667', '12');
INSERT INTO `countries` VALUES ('BO', 'bolivia', 'Bolivia\r\nBolivia, Plurinational state of', '-17', '-65', '9');
INSERT INTO `countries` VALUES ('BR', 'brazil', 'Brazil\r\n', '-10', '-55', '27');
INSERT INTO `countries` VALUES ('BS', 'bahamas', 'Bahamas\r\n', '24.25', '-76', '21');
INSERT INTO `countries` VALUES ('BT', 'bhutan', 'Bhutan\r\n', '27.5', '90.5', '18');
INSERT INTO `countries` VALUES ('BV', 'bouvet-island', 'Bouvet Island\r\n', '-54.4333', '3.4', '0');
INSERT INTO `countries` VALUES ('BW', 'botswana', 'Botswana\r\n', '-22', '24', '10');
INSERT INTO `countries` VALUES ('BY', 'belarus', 'Belarus\r\n', '53', '28', '7');
INSERT INTO `countries` VALUES ('BZ', 'belize', 'Belize\r\n', '17.25', '-88.75', '6');
INSERT INTO `countries` VALUES ('CA', 'canada', 'Canada\r\n', '60', '-95', '13');
INSERT INTO `countries` VALUES ('CC', 'cocos-keeling-islands', 'Cocos (Keeling) Islands\r\n', '-12.5', '96.8333', '0');
INSERT INTO `countries` VALUES ('CD', 'congo-the-democratic-republic-of-the', 'Congo, The Democratic Republic of the\r\n', '-4.038333', '21.758664', '12');
INSERT INTO `countries` VALUES ('CF', 'central-african-republic', 'Central African Republic\r\n', '7', '21', '17');
INSERT INTO `countries` VALUES ('CG', 'congo', 'Congo\r\n', '-1', '15', '10');
INSERT INTO `countries` VALUES ('CH', 'switzerland', 'Switzerland\r\n', '47', '8', '26');
INSERT INTO `countries` VALUES ('CI', 'cote-d-ivoire', 'Côte d\'Ivoire', '8', '-5', '57');
INSERT INTO `countries` VALUES ('CK', 'cook-islands', 'Cook Islands\r\n', '-21.2333', '-159.7667', '0');
INSERT INTO `countries` VALUES ('CL', 'chile', 'Chile', '-30', '-71', '13');
INSERT INTO `countries` VALUES ('CM', 'cameroon', 'Cameroon\r\n', '6', '12', '10');
INSERT INTO `countries` VALUES ('CN', 'china', 'China\r\n', '35', '105', '31');
INSERT INTO `countries` VALUES ('CO', 'colombia', 'Colombia\r\n', '4', '-72', '33');
INSERT INTO `countries` VALUES ('CR', 'costa-rica', 'Costa Rica\r\n', '10', '-84', '7');
INSERT INTO `countries` VALUES ('CU', 'cuba', 'Cuba\r\n', '21.5', '-80', '15');
INSERT INTO `countries` VALUES ('CV', 'cape-verde', 'Cape Verde\r\n', '16', '-24', '16');
INSERT INTO `countries` VALUES ('CX', 'christmas-island', 'Christmas Island\r\n', '-10.5', '105.6667', '0');
INSERT INTO `countries` VALUES ('CY', 'cyprus', 'Cyprus\r\n', '35', '33', '6');
INSERT INTO `countries` VALUES ('CZ', 'czech-republic', 'Czech Republic\r\n', '49.75', '15.5', '29');
INSERT INTO `countries` VALUES ('DE', 'germany', 'Germany\r\n', '51', '9', '16');
INSERT INTO `countries` VALUES ('DJ', 'djibouti', 'Djibouti\r\n', '11.5', '43', '4');
INSERT INTO `countries` VALUES ('DK', 'denmark', 'Denmark\r\n', '56', '10', '15');
INSERT INTO `countries` VALUES ('DM', 'dominica', 'Dominica\r\n', '15.4167', '-61.3333', '10');
INSERT INTO `countries` VALUES ('DO', 'dominican-republic', 'Dominican Republic\r\n', '19', '-70.6667', '30');
INSERT INTO `countries` VALUES ('DZ', 'algeria', 'Algeria\r\n', '28', '3', '48');
INSERT INTO `countries` VALUES ('EC', 'ecuador', 'Ecuador\r\n', '-2', '-77.5', '22');
INSERT INTO `countries` VALUES ('EE', 'estonia', 'Estonia\r\n', '59', '26', '21');
INSERT INTO `countries` VALUES ('EG', 'egypt', 'Egypt\r\n', '27', '30', '26');
INSERT INTO `countries` VALUES ('EH', 'western-sahara', 'Western Sahara\r\n', '24.5', '-13', '0');
INSERT INTO `countries` VALUES ('ER', 'eritrea', 'Eritrea\r\n', '15', '39', '0');
INSERT INTO `countries` VALUES ('ES', 'spain', 'Spain\r\n', '40', '-4', '17');
INSERT INTO `countries` VALUES ('ET', 'ethiopia', 'Ethiopia\r\n', '8', '38', '19');
INSERT INTO `countries` VALUES ('FI', 'finland', 'Finland\r\n', '64', '26', '6');
INSERT INTO `countries` VALUES ('FJ', 'fiji', 'Fiji\r\n', '-18', '175', '5');
INSERT INTO `countries` VALUES ('FK', 'falkland-islands-malvinas', 'Falkland Islands (Malvinas)\r\n', '-51.75', '-59', '0');
INSERT INTO `countries` VALUES ('FM', 'micronesia-federated-states-of', 'Micronesia, Federated States of\r\n', '6.9167', '158.25', '4');
INSERT INTO `countries` VALUES ('FO', 'faroe-islands', 'Faroe Islands\r\n', '62', '-7', '0');
INSERT INTO `countries` VALUES ('FR', 'france', 'France\r\n', '46', '2', '22');
INSERT INTO `countries` VALUES ('GA', 'gabon', 'Gabon', '-1', '11.75', '9');
INSERT INTO `countries` VALUES ('GB', 'united-kingdom', 'United Kingdom', '54', '-2', '252');
INSERT INTO `countries` VALUES ('GD', 'grenada', 'Grenada', '12.1167', '-61.6667', '6');
INSERT INTO `countries` VALUES ('GE', 'georgia', 'Georgia', '42', '43.5', '64');
INSERT INTO `countries` VALUES ('GF', 'french-guiana', 'French Guiana', '4', '-53', '0');
INSERT INTO `countries` VALUES ('GG', 'guernsey', 'Guernsey', '49.465691', '-2.585278', '0');
INSERT INTO `countries` VALUES ('GH', 'ghana', 'Ghana\r\n', '8', '-2', '10');
INSERT INTO `countries` VALUES ('GI', 'gibraltar', 'Gibraltar\r\n', '36.1833', '-5.3667', '0');
INSERT INTO `countries` VALUES ('GL', 'greenland', 'Greenland\r\n', '72', '-40', '3');
INSERT INTO `countries` VALUES ('GM', 'gambia', 'Gambia\r\n', '13.4667', '-16.5667', '6');
INSERT INTO `countries` VALUES ('GN', 'guinea', 'Guinea\r\n', '11', '-10', '34');
INSERT INTO `countries` VALUES ('GP', 'guadeloupe', 'Guadeloupe\r\n', '16.25', '-61.5833', '0');
INSERT INTO `countries` VALUES ('GQ', 'equatorial-guinea', 'Equatorial Guinea\r\n', '2', '10', '7');
INSERT INTO `countries` VALUES ('GR', 'greece', 'Greece\r\n', '39', '22', '51');
INSERT INTO `countries` VALUES ('GS', 'south-georgia-and-the-south-sandwich-islands', 'South Georgia and the South Sandwich Islands\r\n', '-54.5', '-37', '0');
INSERT INTO `countries` VALUES ('GT', 'guatemala', 'Guatemala\r\n', '15.5', '-90.25', '22');
INSERT INTO `countries` VALUES ('GU', 'guam', 'Guam\r\n', '13.4667', '144.7833', '0');
INSERT INTO `countries` VALUES ('GW', 'guinea-bissau', 'Guinea-Bissau\r\n', '12', '-15', '9');
INSERT INTO `countries` VALUES ('GY', 'guyana', 'Guyana\r\n', '5', '-59', '10');
INSERT INTO `countries` VALUES ('HK', 'hong-kong', 'Hong Kong\r\n', '22.25', '114.1667', '0');
INSERT INTO `countries` VALUES ('HM', 'heard-island-and-mcdonald-islands', 'Heard Island and McDonald Islands\r\n', '-53.1', '72.5167', '0');
INSERT INTO `countries` VALUES ('HN', 'honduras', 'Honduras\r\n', '15', '-86.5', '18');
INSERT INTO `countries` VALUES ('HR', 'croatia', 'Croatia\r\n', '45.1667', '15.5', '21');
INSERT INTO `countries` VALUES ('HT', 'haiti', 'Haiti\r\n', '19', '-72.4167', '9');
INSERT INTO `countries` VALUES ('HU', 'hungary', 'Hungary\r\n', '47', '20', '40');
INSERT INTO `countries` VALUES ('ID', 'indonesia', 'Indonesia\r\n', '-5', '120', '30');
INSERT INTO `countries` VALUES ('IE', 'ireland', 'Ireland\r\n', '53', '-8', '26');
INSERT INTO `countries` VALUES ('IL', 'israel', 'Israel\r\n', '31.5', '34.75', '6');
INSERT INTO `countries` VALUES ('IM', 'isle-of-man', 'Isle of Man\r\n', '54.236107', '-4.548056', '0');
INSERT INTO `countries` VALUES ('IN', 'india', 'India\r\n', '20', '77', '35');
INSERT INTO `countries` VALUES ('IO', 'british-indian-ocean-territory', 'British Indian Ocean Territory\r\n', '-6', '71.5', '0');
INSERT INTO `countries` VALUES ('IQ', 'iraq', 'Iraq\r\n', '33', '44', '18');
INSERT INTO `countries` VALUES ('IR', 'iran-islamic-republic-of', 'Iran, Islamic Republic of\r\n', '32', '53', '28');
INSERT INTO `countries` VALUES ('IS', 'iceland', 'Iceland\r\n', '65', '-18', '37');
INSERT INTO `countries` VALUES ('IT', 'italy', 'Italy', '42.8333', '12.8333', '20');
INSERT INTO `countries` VALUES ('JE', 'jersey', 'Jersey\r\n', '49.214439', '-2.13125', '0');
INSERT INTO `countries` VALUES ('JM', 'jamaica', 'Jamaica\r\n', '18.25', '-77.5', '14');
INSERT INTO `countries` VALUES ('JO', 'jordan', 'Jordan\r\n', '31', '36', '8');
INSERT INTO `countries` VALUES ('JP', 'japan', 'Japan\r\n', '36', '138', '47');
INSERT INTO `countries` VALUES ('KE', 'kenya', 'Kenya\r\n', '1', '38', '8');
INSERT INTO `countries` VALUES ('KG', 'kyrgyzstan', 'Kyrgyzstan\r\n', '41', '75', '8');
INSERT INTO `countries` VALUES ('KH', 'cambodia', 'Cambodia\r\n', '13', '105', '20');
INSERT INTO `countries` VALUES ('KI', 'kiribati', 'Kiribati\r\n', '1.4167', '173', '3');
INSERT INTO `countries` VALUES ('KM', 'comoros', 'Comoros\r\n', '-12.1667', '44.25', '3');
INSERT INTO `countries` VALUES ('KN', 'saint-kitts-and-nevis', 'Saint Kitts and Nevis\r\n', '17.3333', '-62.75', '14');
INSERT INTO `countries` VALUES ('KP', 'korea-democratic-people-s-republic-of', 'Korea, Democratic People&#39;s Republic of\r\n', '40', '127', '13');
INSERT INTO `countries` VALUES ('KR', 'korea-republic-of', 'Korea, Republic of\r\n', '37', '127.5', '16');
INSERT INTO `countries` VALUES ('KW', 'kuwait', 'Kuwait\r\n', '29.5', '45.75', '4');
INSERT INTO `countries` VALUES ('KY', 'cayman-islands', 'Cayman Islands\r\n', '19.5', '-80.5', '8');
INSERT INTO `countries` VALUES ('KZ', 'kazakhstan', 'Kazakhstan\r\n', '48', '68', '17');
INSERT INTO `countries` VALUES ('LA', 'lao-people-s-democratic-republic', 'Lao People&#39;s Democratic Republic\r\n', '18', '105', '13');
INSERT INTO `countries` VALUES ('LB', 'lebanon', 'Lebanon\r\n', '33.8333', '35.8333', '6');
INSERT INTO `countries` VALUES ('LC', 'saint-lucia', 'Saint Lucia\r\n', '13.8833', '-61.1333', '11');
INSERT INTO `countries` VALUES ('LI', 'liechtenstein', 'Liechtenstein\r\n', '47.1667', '9.5333', '11');
INSERT INTO `countries` VALUES ('LK', 'sri-lanka', 'Sri Lanka\r\n', '7', '81', '24');
INSERT INTO `countries` VALUES ('LR', 'liberia', 'Liberia\r\n', '6.5', '-9.5', '10');
INSERT INTO `countries` VALUES ('LS', 'lesotho', 'Lesotho\r\n', '-29.5', '28.5', '10');
INSERT INTO `countries` VALUES ('LT', 'lithuania', 'Lithuania\r\n', '56', '24', '10');
INSERT INTO `countries` VALUES ('LU', 'luxembourg', 'Luxembourg\r\n', '49.75', '6.1667', '3');
INSERT INTO `countries` VALUES ('LV', 'latvia', 'Latvia\r\n', '57', '25', '33');
INSERT INTO `countries` VALUES ('LY', 'libyan-arab-jamahiriya', 'Libyan Arab Jamahiriya\r\n', '25', '17', '25');
INSERT INTO `countries` VALUES ('MA', 'morocco', 'Morocco\r\n', '32', '-5', '39');
INSERT INTO `countries` VALUES ('MC', 'monaco', 'Monaco\r\n', '43.7333', '7.4', '3');
INSERT INTO `countries` VALUES ('MD', 'moldova-republic-of', 'Moldova, Republic of\r\n', '47', '29', '11');
INSERT INTO `countries` VALUES ('ME', 'montenegro', 'Montenegro\r\n', '42.572638', '18.807756', '0');
INSERT INTO `countries` VALUES ('MF', 'saint-martin', 'Saint Martin', '0', '0', '0');
INSERT INTO `countries` VALUES ('MG', 'madagascar', 'Madagascar\r\n', '-20', '47', '6');
INSERT INTO `countries` VALUES ('MH', 'marshall-islands', 'Marshall Islands\r\n', '9', '168', '0');
INSERT INTO `countries` VALUES ('MK', 'macedonia', 'Macedonia\r\n', '41.8333', '22', '123');
INSERT INTO `countries` VALUES ('ML', 'mali', 'Mali\r\n', '17', '-4', '9');
INSERT INTO `countries` VALUES ('MM', 'myanmar', 'Myanmar\r\n', '21.913965', '95.956223', '15');
INSERT INTO `countries` VALUES ('MN', 'mongolia', 'Mongolia\r\n', '46', '105', '24');
INSERT INTO `countries` VALUES ('MO', 'macao', 'Macao\r\n', '22.1667', '113.55', '2');
INSERT INTO `countries` VALUES ('MP', 'northern-mariana-islands', 'Northern Mariana Islands\r\n', '15.2', '145.75', '0');
INSERT INTO `countries` VALUES ('MQ', 'martinique', 'Martinique\r\n', '14.6667', '-61', '0');
INSERT INTO `countries` VALUES ('MR', 'mauritania', 'Mauritania\r\n', '20', '-12', '12');
INSERT INTO `countries` VALUES ('MS', 'montserrat', 'Montserrat\r\n', '16.75', '-62.2', '3');
INSERT INTO `countries` VALUES ('MT', 'malta', 'Malta\r\n', '35.8333', '14.5833', '0');
INSERT INTO `countries` VALUES ('MU', 'mauritius', 'Mauritius\r\n', '-20.2833', '57.55', '12');
INSERT INTO `countries` VALUES ('MV', 'maldives', 'Maldives\r\n', '3.25', '73', '19');
INSERT INTO `countries` VALUES ('MW', 'malawi', 'Malawi\r\n', '-13.5', '34', '27');
INSERT INTO `countries` VALUES ('MX', 'mexico', 'Mexico\r\n', '23', '-102', '32');
INSERT INTO `countries` VALUES ('MY', 'malaysia', 'Malaysia\r\n', '2.5', '112.5', '15');
INSERT INTO `countries` VALUES ('MZ', 'mozambique', 'Mozambique\r\n', '-18.25', '35', '10');
INSERT INTO `countries` VALUES ('NA', 'namibia', 'Namibia\r\n', '-22', '17', '38');
INSERT INTO `countries` VALUES ('NC', 'new-caledonia', 'New Caledonia\r\n', '-21.5', '165.5', '0');
INSERT INTO `countries` VALUES ('NE', 'niger', 'Niger\r\n', '16', '8', '7');
INSERT INTO `countries` VALUES ('NF', 'norfolk-island', 'Norfolk Island\r\n', '-29.0333', '167.95', '0');
INSERT INTO `countries` VALUES ('NG', 'nigeria', 'Nigeria\r\n', '10', '8', '37');
INSERT INTO `countries` VALUES ('NI', 'nicaragua', 'Nicaragua\r\n', '13', '-85', '16');
INSERT INTO `countries` VALUES ('NL', 'netherlands', 'Netherlands\r\n', '52.5', '5.75', '16');
INSERT INTO `countries` VALUES ('NO', 'norway', 'Norway', '62', '10', '19');
INSERT INTO `countries` VALUES ('NP', 'nepal', 'Nepal\r\n', '28', '84', '14');
INSERT INTO `countries` VALUES ('NR', 'nauru', 'Nauru\r\n', '-0.5333', '166.9167', '14');
INSERT INTO `countries` VALUES ('NU', 'niue', 'Niue\r\n', '-19.0333', '-169.8667', '0');
INSERT INTO `countries` VALUES ('NZ', 'new-zealand', 'New Zealand\r\n', '-41', '174', '105');
INSERT INTO `countries` VALUES ('OM', 'oman', 'Oman\r\n', '21', '57', '8');
INSERT INTO `countries` VALUES ('PA', 'panama', 'Panama\r\n', '9', '-80', '10');
INSERT INTO `countries` VALUES ('PE', 'peru', 'Peru\r\n', '-10', '-76', '25');
INSERT INTO `countries` VALUES ('PF', 'french-polynesia', 'French Polynesia\r\n', '-15', '-140', '0');
INSERT INTO `countries` VALUES ('PG', 'papua-new-guinea', 'Papua New Guinea\r\n', '-6', '147', '20');
INSERT INTO `countries` VALUES ('PH', 'philippines', 'Philippines\r\n', '13', '122', '134');
INSERT INTO `countries` VALUES ('PK', 'pakistan', 'Pakistan\r\n', '30', '70', '8');
INSERT INTO `countries` VALUES ('PL', 'poland', 'Poland\r\n', '52', '20', '65');
INSERT INTO `countries` VALUES ('PM', 'saint-pierre-and-miquelon', 'Saint Pierre and Miquelon\r\n', '46.8333', '-56.3333', '0');
INSERT INTO `countries` VALUES ('PN', 'pitcairn', 'Pitcairn\r\n', '-24.703615', '-127.439308', '0');
INSERT INTO `countries` VALUES ('PR', 'puerto-rico', 'Puerto Rico\r\n', '18.25', '-66.5', '0');
INSERT INTO `countries` VALUES ('PS', 'palestinian-territory', 'Palestinian Territory, Occupied', '32', '35.25', '0');
INSERT INTO `countries` VALUES ('PT', 'portugal', 'Portugal\r\n', '39.5', '-8', '20');
INSERT INTO `countries` VALUES ('PW', 'palau', 'Palau\r\n', '7.5', '134.5', '0');
INSERT INTO `countries` VALUES ('PY', 'paraguay', 'Paraguay\r\n', '-23', '-58', '19');
INSERT INTO `countries` VALUES ('QA', 'qatar', 'Qatar\r\n', '25.5', '51.25', '10');
INSERT INTO `countries` VALUES ('RE', 'reunion', 'Réunion', '-21.1', '55.6', '0');
INSERT INTO `countries` VALUES ('RO', 'romania', 'Romania\r\n', '46', '25', '42');
INSERT INTO `countries` VALUES ('RS', 'serbia', 'Serbia\r\n', '44.015194', '20.729164', '0');
INSERT INTO `countries` VALUES ('RU', 'russian-federation', 'Russian Federation\r\n', '60', '100', '89');
INSERT INTO `countries` VALUES ('RW', 'rwanda', 'Rwanda\r\n', '-2', '30', '10');
INSERT INTO `countries` VALUES ('SA', 'saudi-arabia', 'Saudi Arabia\r\n', '25', '45', '14');
INSERT INTO `countries` VALUES ('SB', 'solomon-islands', 'Solomon Islands\r\n', '-8', '159', '7');
INSERT INTO `countries` VALUES ('SC', 'seychelles', 'Seychelles\r\n', '-4.5833', '55.6667', '23');
INSERT INTO `countries` VALUES ('SD', 'sudan', 'Sudan\r\n', '15', '30', '8');
INSERT INTO `countries` VALUES ('SE', 'sweden', 'Sweden\r\n', '62', '15', '26');
INSERT INTO `countries` VALUES ('SG', 'singapore', 'Singapore\r\n', '1.3667', '103.8', '0');
INSERT INTO `countries` VALUES ('SH', 'saint-helena', 'Saint Helena\r\n', '-15.9333', '-5.7', '3');
INSERT INTO `countries` VALUES ('SI', 'slovenia', 'Slovenia\r\n', '46', '15', '141');
INSERT INTO `countries` VALUES ('SJ', 'svalbard-and-jan-mayen', 'Svalbard and Jan Mayen\r\n', '78', '20', '0');
INSERT INTO `countries` VALUES ('SK', 'slovakia', 'Slovakia\r\n', '48.6667', '19.5', '8');
INSERT INTO `countries` VALUES ('SL', 'sierra-leone', 'Sierra Leone\r\n', '8.5', '-11.5', '4');
INSERT INTO `countries` VALUES ('SM', 'san-marino', 'San Marino\r\n', '43.7667', '12.4167', '9');
INSERT INTO `countries` VALUES ('SN', 'senegal', 'Senegal\r\n', '14', '-14', '10');
INSERT INTO `countries` VALUES ('SO', 'somalia', 'Somalia\r\n', '10', '49', '16');
INSERT INTO `countries` VALUES ('SR', 'suriname', 'Suriname\r\n', '4', '-56', '10');
INSERT INTO `countries` VALUES ('ST', 'sao-tome-and-principe', 'Sao Tome and Principe\r\n', '1', '7', '2');
INSERT INTO `countries` VALUES ('SV', 'el-salvador', 'El Salvador\r\n', '13.8333', '-88.9167', '14');
INSERT INTO `countries` VALUES ('SY', 'syrian-arab-republic', 'Syrian Arab Republic\r\n', '35', '38', '14');
INSERT INTO `countries` VALUES ('SZ', 'swaziland', 'Swaziland\r\n', '-26.5', '31.5', '5');
INSERT INTO `countries` VALUES ('TC', 'turks-and-caicos-islands', 'Turks and Caicos Islands\r\n', '21.75', '-71.5833', '0');
INSERT INTO `countries` VALUES ('TD', 'chad', 'Chad', '15', '19', '14');
INSERT INTO `countries` VALUES ('TF', 'french-southern-territories', 'French Southern Territories', '-49.44996', '70.024982', '0');
INSERT INTO `countries` VALUES ('TG', 'togo', 'Togo', '8', '1.1667', '21');
INSERT INTO `countries` VALUES ('TH', 'thailand', 'Thailand', '15', '100', '73');
INSERT INTO `countries` VALUES ('TJ', 'tajikistan', 'Tajikistan', '39', '71', '3');
INSERT INTO `countries` VALUES ('TK', 'tokelau', 'Tokelau', '-9', '-172', '0');
INSERT INTO `countries` VALUES ('TL', 'timor-leste', 'Timor-Leste', '-8.874217', '125.727539', '0');
INSERT INTO `countries` VALUES ('TM', 'turkmenistan', 'Turkmenistan\r\n', '40', '60', '5');
INSERT INTO `countries` VALUES ('TN', 'tunisia', 'Tunisia\r\n', '34', '9', '24');
INSERT INTO `countries` VALUES ('TO', 'tonga', 'Tonga\r\n', '-20', '-175', '3');
INSERT INTO `countries` VALUES ('TR', 'turkey', 'Turkey', '39', '35', '81');
INSERT INTO `countries` VALUES ('TT', 'trinidad-and-tobago', 'Trinidad and Tobago\r\n', '11', '-61', '12');
INSERT INTO `countries` VALUES ('TV', 'tuvalu', 'Tuvalu\r\n', '-8', '178', '0');
INSERT INTO `countries` VALUES ('TW', 'taiwan', 'Taiwan\r\n', '23.5', '121', '4');
INSERT INTO `countries` VALUES ('TZ', 'tanzania-united-republic-of', 'Tanzania, United Republic of\r\n', '-6', '35', '25');
INSERT INTO `countries` VALUES ('UA', 'ukraine', 'Ukraine\r\n', '49', '32', '27');
INSERT INTO `countries` VALUES ('UG', 'uganda', 'Uganda\r\n', '1', '32', '38');
INSERT INTO `countries` VALUES ('UM', 'united-states-minor-outlying-islands', 'United States Minor Outlying Islands\r\n', '19.2833', '166.6', '0');
INSERT INTO `countries` VALUES ('US', 'united-states', 'United States\r\n', '38', '-97', '62');
INSERT INTO `countries` VALUES ('UY', 'uruguay', 'Uruguay\r\n', '-33', '-56', '19');
INSERT INTO `countries` VALUES ('UZ', 'uzbekistan', 'Uzbekistan\r\n', '41', '64', '14');
INSERT INTO `countries` VALUES ('VA', 'holy-see-vatican-city-state', 'Holy See (Vatican City State)\r\n', '41.9', '12.45', '0');
INSERT INTO `countries` VALUES ('VC', 'saint-vincent-and-the-grenadines', 'Saint Vincent and the Grenadines\r\n', '13.25', '-61.2', '6');
INSERT INTO `countries` VALUES ('VE', 'venezuela', 'Venezuela, Bolivarian Republic of', '8', '-66', '25');
INSERT INTO `countries` VALUES ('VG', 'virgin-islands-british', 'Virgin Islands, British\r\n', '18.5', '-64.5', '0');
INSERT INTO `countries` VALUES ('VI', 'virgin-islands-us', 'Virgin Islands, U.S.\r\n', '18.3333', '-64.8333', '0');
INSERT INTO `countries` VALUES ('VN', 'vietnam', 'Viet Nam', '16', '106', '53');
INSERT INTO `countries` VALUES ('VU', 'vanuatu', 'Vanuatu\r\n', '-16', '167', '14');
INSERT INTO `countries` VALUES ('WF', 'wallis-and-futuna', 'Wallis and Futuna\r\n', '-13.3', '-176.2', '0');
INSERT INTO `countries` VALUES ('WS', 'samoa', 'Samoa\r\n', '-13.5833', '-172.3333', '10');
INSERT INTO `countries` VALUES ('YE', 'yemen', 'Yemen\r\n', '15', '48', '16');
INSERT INTO `countries` VALUES ('YT', 'mayotte', 'Mayotte\r\n', '-12.8333', '45.1667', '0');
INSERT INTO `countries` VALUES ('ZA', 'south-africa', 'South Africa\r\n', '-29', '24', '9');
INSERT INTO `countries` VALUES ('ZM', 'zambia', 'Zambia\r\n', '-15', '30', '9');
INSERT INTO `countries` VALUES ('ZW', 'zimbabwe', 'Zimbabwe', '-20', '30', '10');
